/**
 * Type-safe models for the local database.
 *
 * Conventions (must stay in sync with `migrations.ts`):
 * - Money is ALWAYS stored as an integer in the smallest currency unit
 *   (e.g. paisa for PKR). Conversion to a display string happens only in the
 *   UI layer via `formatCurrency`.
 * - Timestamps (`createdAt`, `updatedAt`) and record dates (`date`) are
 *   epoch MILLISECONDS as integers.
 * - SQLite has no booleans: `isDefault` maps to an INTEGER 0/1 column and is
 *   converted in the category repository.
 */

export const CATEGORY_TYPES = ['expense', 'income'] as const;
export type CategoryType = (typeof CATEGORY_TYPES)[number];

export const PAYMENT_METHODS = [
  'cash',
  'card',
  'bank_transfer',
  'mobile_wallet',
  'other',
] as const;
export type PaymentMethod = (typeof PAYMENT_METHODS)[number];

/* ---------------------------------- Category --------------------------------- */

export interface Category {
  id: number;
  name: string;
  /**
   * Stable icon key (e.g. 'cart', 'bus'). The UI layer maps keys to actual
   * glyphs; the database never stores UI-specific values.
   */
  icon: string;
  type: CategoryType;
  isDefault: boolean;
  /**
   * false = archived/disabled. Disabled categories stay resolvable for
   * historical records and remain visible in management, but are excluded
   * from new-transaction pickers. Added by migration 003 (defaults true).
   */
  isActive: boolean;
  createdAt: number;
}

export interface CategoryDraft {
  name: string;
  icon: string;
  type: CategoryType;
  isDefault?: boolean;
}

/**
 * Fields allowed on update. `type` is intentionally NOT patchable — moving a
 * category between expense/income would silently corrupt existing records.
 */
export interface CategoryPatch {
  name?: string;
  icon?: string;
  isDefault?: boolean;
  /** Archive/restore a category without touching its historical records. */
  isActive?: boolean;
}

/* ---------------------------------- Expense ---------------------------------- */

export interface Expense {
  id: number;
  /** Amount in minor units (paisa), always > 0. */
  amount: number;
  title: string;
  categoryId: number;
  /** When the expense happened (epoch millis). */
  date: number;
  paymentMethod: PaymentMethod;
  note: string | null;
  createdAt: number;
  updatedAt: number;
  /**
   * Set on transactions GENERATED by a recurring rule (migration 004);
   * null/absent for manual records. Edits never change it — historical
   * generated rows stay normal, immutable transaction history.
   */
  recurringRuleId?: number | null;
}

export interface ExpenseDraft {
  amount: number;
  title: string;
  categoryId: number;
  date: number;
  paymentMethod: PaymentMethod;
  note?: string | null;
}

export interface ExpensePatch {
  amount?: number;
  title?: string;
  categoryId?: number;
  date?: number;
  paymentMethod?: PaymentMethod;
  note?: string | null;
}

export interface ExpenseFilter {
  categoryId?: number;
  paymentMethod?: PaymentMethod;
  /** Inclusive lower bound on `date` (epoch millis). */
  fromDate?: number;
  /** Inclusive upper bound on `date` (epoch millis). */
  toDate?: number;
  /** Inclusive lower bound on `amount` (minor units, > 0). Phase 11. */
  minAmount?: number;
  /** Inclusive upper bound on `amount` (minor units, > 0). Phase 11. */
  maxAmount?: number;
  /**
   * `true` → only rows GENERATED by a recurring rule
   * (`recurring_rule_id IS NOT NULL`); `false` → only manual rows
   * (`IS NULL`); `undefined` → both. Phase 11 — never inferred from
   * title/date; the column is the single source of truth.
   */
  recurring?: boolean;
  /**
   * Case-insensitive substring match against `title` OR `note` OR the
   * joined category `name` OR the `payment_method` value (Phase 11 —
   * whitespace-normalized; SQL LIKE wildcards in the term are matched
   * literally).
   */
  search?: string;
  limit?: number;
  offset?: number;
  /**
   * `amountDesc` (Phase 9) backs the "largest transaction" report insight;
   * ties resolve to the OLDEST row (id ASC) so results stay deterministic.
   * `amountAsc` (Phase 11) is the same contract in the other direction.
   */
  order?: 'dateDesc' | 'dateAsc' | 'amountDesc' | 'amountAsc';
}

/** Expense joined with its category — what list screens display. */
export interface ExpenseWithCategory extends Expense {
  categoryName: string;
  categoryIcon: string;
}

/** Aggregated spending per category, as returned by `sumByCategory`. */
export interface ExpenseCategoryTotal {
  categoryId: number;
  total: number;
}

/**
 * Spending AND frequency per category, as returned by `sumCountByCategory`
 * (Phase 9). One grouped query powers the category comparison list, the
 * "most frequent category" insight and per-category transaction counts —
 * callers must not loop per-category queries over this (no N+1).
 */
export interface ExpenseCategoryAggregate {
  categoryId: number;
  total: number;
  transactionCount: number;
}

/**
 * Aggregated spending for ONE calendar day, as returned by `sumByDay`.
 *
 * `dayIndex` is the 0-based offset from the `fromDate` anchor passed to
 * `sumByDay`, so it stays exact across DST transitions. Callers that need a
 * timestamp combine it with their own calendar-day list (see the reports
 * feature's `buildDailySeries`).
 */
export interface ExpenseDayTotal {
  dayIndex: number;
  total: number;
}

/* ----------------------------------- Income ---------------------------------- */

export interface Income {
  id: number;
  /** Amount in minor units (paisa), always > 0. */
  amount: number;
  /** Free-text source (e.g. 'Salary'). Kept as TEXT by design — see README. */
  source: string;
  /** When the income was received (epoch millis). */
  date: number;
  note: string | null;
  createdAt: number;
  updatedAt: number;
  /** Set on transactions GENERATED by a recurring rule (migration 004). */
  recurringRuleId?: number | null;
}

export interface IncomeDraft {
  amount: number;
  source: string;
  date: number;
  note?: string | null;
}

export interface IncomePatch {
  amount?: number;
  source?: string;
  date?: number;
  note?: string | null;
}

export interface IncomeFilter {
  fromDate?: number;
  toDate?: number;
  /** Inclusive lower bound on `amount` (minor units, > 0). Phase 11. */
  minAmount?: number;
  /** Inclusive upper bound on `amount` (minor units, > 0). Phase 11. */
  maxAmount?: number;
  /** Same contract as `ExpenseFilter.recurring` (Phase 11). */
  recurring?: boolean;
  /**
   * Exact source match (Phase 9) — income has no category FK, so the
   * category-detail screen filters rows by the exact stored `source` text
   * (the same string `sumBySource` groups by).
   */
  source?: string;
  /**
   * Case-insensitive substring match against `source` OR `note`
   * (whitespace-normalized since Phase 11; SQL LIKE wildcards in the term
   * are matched literally).
   */
  search?: string;
  limit?: number;
  offset?: number;
  /** `amountDesc` (Phase 9) backs the largest-transaction insight. */
  order?: 'dateDesc' | 'dateAsc' | 'amountDesc' | 'amountAsc';
}

/**
 * Aggregated income per source, as returned by `sumBySource` (Phase 9).
 * `source` is the exact free-text value stored on each income row.
 */
export interface IncomeSourceAggregate {
  source: string;
  total: number;
  transactionCount: number;
}

/**
 * Aggregated income for ONE calendar day, as returned by
 * `IncomeRepository.sumByDay`. Same `dayIndex` anchoring contract as
 * `ExpenseDayTotal` (0-based offset from the passed local-midnight
 * `fromDate`, exact across DST transitions).
 */
export interface IncomeDayTotal {
  dayIndex: number;
  total: number;
}

/* ----------------------------------- Budget ---------------------------------- */

/** Per-category budget for one month (table `budgets`). */
export interface Budget {
  id: number;
  categoryId: number;
  /** Monthly limit in minor units (paisa), always > 0. */
  amount: number;
  /** 1-12. */
  month: number;
  /** 2000-2100. */
  year: number;
  createdAt: number;
  updatedAt: number;
}

export interface BudgetDraft {
  categoryId: number;
  amount: number;
  month: number;
  year: number;
}

export interface BudgetPatch {
  amount?: number;
  month?: number;
  year?: number;
}

/** Budget joined with its category, as returned by `listByMonth`. */
export interface BudgetWithCategory extends Budget {
  categoryName: string;
  categoryIcon: string;
}

/* ------------------------------- MonthlyBudget ------------------------------- */

/**
 * Overall spending budget for one month, not tied to any category
 * (table `monthly_budgets`, migration 002). Category budgets live in
 * `budgets`; this is the month-level limit shown on the Budget screen and
 * dashboard. One row per (year, month) — enforced by a unique index.
 */
export interface MonthlyBudget {
  id: number;
  /** Monthly limit in minor units (paisa), always > 0. */
  amount: number;
  /** 1-12. */
  month: number;
  /** 2000-2100. */
  year: number;
  createdAt: number;
  updatedAt: number;
}

export interface MonthlyBudgetDraft {
  amount: number;
  month: number;
  year: number;
}

export interface MonthlyBudgetPatch {
  amount?: number;
  month?: number;
  year?: number;
}

/* ------------------------------ RecurringTransaction -------------------------- */

/** Supported recurrence frequencies. Simple and mobile-friendly by design. */
export const RECURRING_FREQUENCIES = ['daily', 'weekly', 'monthly'] as const;
export type RecurringFrequency = (typeof RECURRING_FREQUENCIES)[number];

/**
 * A reusable rule that generates NORMAL expense/income rows on schedule
 * (table `recurring_transactions`, migration 004).
 *
 * A recurring rule is NOT a transaction: generated rows land in the regular
 * `expenses` / `income` tables and appear everywhere ordinary transactions
 * appear. Occurrence timestamps are local NOON epoch millis (same DST-safe
 * convention as record dates).
 */
export interface RecurringTransaction {
  id: number;
  /** Which side of the ledger the generated rows belong to. */
  type: CategoryType;
  /** Amount in minor units (paisa), always > 0. Never currency-converted. */
  amount: number;
  /** Expense title, or the income `source` of generated rows. */
  title: string;
  /** Expense rules only — income has no category FK (see migration 001). */
  categoryId: number | null;
  frequency: RecurringFrequency;
  /** First occurrence (local noon). Informational anchor after creation. */
  startDate: number;
  /** Next due occurrence (local noon). Advanced by the generation engine. */
  nextOccurrenceAt: number;
  /** Inclusive last occurrence (local noon); null = runs indefinitely. */
  endDate: number | null;
  /** Expense rules only — generated expenses reuse it for `payment_method`. */
  paymentMethod: PaymentMethod | null;
  note: string | null;
  /** false = paused: stored but never generates. */
  isActive: boolean;
  createdAt: number;
  updatedAt: number;
}

export interface RecurringTransactionDraft {
  type: CategoryType;
  amount: number;
  title: string;
  /** Required for expense rules; must stay null for income rules. */
  categoryId?: number | null;
  frequency: RecurringFrequency;
  /** First occurrence (local noon). */
  startDate: number;
  /** Defaults to `startDate` — the rule becomes due on its first occurrence. */
  nextOccurrenceAt?: number;
  endDate?: number | null;
  /** Required for expense rules; must stay null for income rules. */
  paymentMethod?: PaymentMethod | null;
  note?: string | null;
  isActive?: boolean;
}

/**
 * Fields allowed on update. `type` and `startDate` are intentionally NOT
 * patchable — moving a rule between expense/income (or re-anchoring its
 * history) would corrupt the generation semantics; delete and recreate
 * instead. `endDate: null` clears the end date.
 */
export interface RecurringTransactionPatch {
  amount?: number;
  title?: string;
  categoryId?: number;
  frequency?: RecurringFrequency;
  nextOccurrenceAt?: number;
  endDate?: number | null;
  paymentMethod?: PaymentMethod | null;
  note?: string | null;
}

export interface RecurringFilter {
  type?: CategoryType;
  isActive?: boolean;
}

/** Rule joined with its category — what the list screens display. */
export interface RecurringWithCategory extends RecurringTransaction {
  /** Null for income rules (which have no category). */
  categoryName: string | null;
  categoryIcon: string | null;
}

/* ---------------------------------- Setting ---------------------------------- */

export interface Setting {
  key: string;
  value: string;
}
