import type {PaymentMethod} from '@/database/models';
import type {CategoryTotal} from '@/features/expenses/types';

/**
 * Shared, UI-facing transaction model.
 *
 * Expenses and income stay SEPARATE database tables (see migration 001);
 * this is a lightweight view model that normalizes both into one shape so
 * list screens can sort, filter and render a mixed ledger without caring
 * where each row came from.
 */
export interface TransactionItem {
  /** Stable list key, unique across both tables: `expense-12` / `income-3`. */
  key: string;
  /** Which table the row came from — drives color, editor and filters. */
  type: 'expense' | 'income';
  /** Row id within its own table. */
  id: number;
  /** When the transaction happened (epoch millis). */
  date: number;
  /** Amount in minor units (paisa), always > 0. */
  amount: number;
  /** Expense title or income source — the row's primary label. */
  title: string;
  /** Category name (expenses only; income has no category FK). */
  category: string | null;
  /** Stable icon key resolved via `categoryIconName`. */
  icon: string;
  note: string | null;
  /** Expense only — income is not paid via a payment method. */
  paymentMethod?: PaymentMethod;
  /**
   * Set when the row was GENERATED by a recurring rule (migration 004);
   * absent/null for manual records. Drives the small recurring indicator
   * in `TransactionRow` — generated rows remain normal transactions.
   */
  recurringRuleId?: number | null;
}

/** Which side(s) of the ledger a transaction list should include. */
export type TransactionTypeFilter = 'all' | 'expense' | 'income';

export const TRANSACTION_TYPE_FILTERS: {
  value: TransactionTypeFilter;
  label: string;
}[] = [
  {value: 'all', label: 'All'},
  {value: 'expense', label: 'Expenses'},
  {value: 'income', label: 'Income'},
];

/**
 * Date-window options for the Transactions browser (Phase 11). Extends the
 * old `PeriodFilter` (all/thisMonth/last7Days) with today/thisWeek/
 * lastMonth/custom; boundaries resolve through the SHARED date utilities —
 * there is exactly one date system in the app.
 */
export type TransactionDatePeriod =
  'all' | 'today' | 'thisWeek' | 'thisMonth' | 'lastMonth' | 'custom';

export const TRANSACTION_DATE_PERIODS: {
  value: TransactionDatePeriod;
  label: string;
}[] = [
  {value: 'all', label: 'All time'},
  {value: 'today', label: 'Today'},
  {value: 'thisWeek', label: 'This week'},
  {value: 'thisMonth', label: 'This month'},
  {value: 'lastMonth', label: 'Last month'},
  {value: 'custom', label: 'Custom'},
];

/** Inclusive local epoch-millis window (both ends bounded). */
export interface TransactionCustomRange {
  fromDate: number;
  toDate: number;
}

/** Whether the ledger shows rule-generated rows, manual rows, or both. */
export type TransactionRecurringFilter = 'all' | 'recurring' | 'manual';

export const TRANSACTION_RECURRING_FILTERS: {
  value: TransactionRecurringFilter;
  label: string;
}[] = [
  {value: 'all', label: 'All'},
  {value: 'recurring', label: 'Recurring'},
  {value: 'manual', label: 'Manual'},
];

/**
 * Sort orders for the Transactions browser (Phase 11). Mapped onto the
 * repositories' whitelisted SQL `order` values — never built from user
 * input. Deterministic: each SQL order tie-breaks on id, and the merge
 * keeps same-key ties in a stable expense-then-income order.
 */
export type TransactionSort = 'newest' | 'oldest' | 'highest' | 'lowest';

export const TRANSACTION_SORT_OPTIONS: {
  value: TransactionSort;
  label: string;
}[] = [
  {value: 'newest', label: 'Newest first'},
  {value: 'oldest', label: 'Oldest first'},
  {value: 'highest', label: 'Highest amount'},
  {value: 'lowest', label: 'Lowest amount'},
];

/** What the Transactions screen asks the feature service for. */
export interface TransactionQuery {
  type?: TransactionTypeFilter;
  /**
   * Substring matched against expense title/note/category name/payment
   * method and income source/note. Whitespace-normalized + SQL-LIKE-escaped
   * at the repository layer.
   */
  search?: string;
  /** `null`/`undefined` means every category. Income has no category. */
  categoryId?: number | null;
  /** Expense-side payment method filter; income rows are excluded while set. */
  paymentMethod?: PaymentMethod | null;
  /** Rule-generated vs manual rows (drives `recurring_rule_id` SQL). */
  recurring?: TransactionRecurringFilter;
  /** Date window; `custom` pairs with `customRange`. */
  period?: TransactionDatePeriod;
  /** Inclusive local-day range used when `period` is `'custom'`. */
  customRange?: TransactionCustomRange | null;
  /** Inclusive minimum amount (minor units). */
  minAmount?: number | null;
  /** Inclusive maximum amount (minor units). */
  maxAmount?: number | null;
  /** Sort order; SQL-side. Defaults to `newest`. */
  sort?: TransactionSort;
  /** Zero-based page index. */
  page?: number;
  /** Rows per page; defaults to `TRANSACTION_PAGE_SIZE`. */
  pageSize?: number;
}

export interface TransactionPage {
  items: TransactionItem[];
  /** Whether another page exists after this one. */
  hasMore: boolean;
}

/** Default page size for the transactions list. */
export const TRANSACTION_PAGE_SIZE = 30;

/** Everything the dashboard renders, computed in one service call. */
export interface DashboardSnapshot {
  /** Received today (minor units). */
  todayIncome: number;
  /** Spent today (minor units). */
  todayExpense: number;
  /** todayIncome - todayExpense. */
  todayBalance: number;
  /** Received in the current calendar month (minor units). */
  monthIncome: number;
  /** Spent in the current calendar month (minor units). */
  monthExpense: number;
  /** monthIncome - monthExpense. */
  monthBalance: number;
  /** Current-month expense totals per category, largest first. */
  categoryTotals: CategoryTotal[];
  /** Newest transactions of either type, any date. */
  recent: TransactionItem[];
}
