import type {ExpenseWithCategory, Income} from '@/database/models';

import {formatMinorAsDecimal} from '@/utils/format';

// Re-exported so backup/CSV consumers (and tests) keep a single import site.
export {formatMinorAsDecimal};

/**
 * CSV export of the transaction ledger — pure string building, no I/O.
 *
 * Money rules (spec §6): amounts leave this module exactly as stored — the
 * integer minor units are rendered as an exact decimal string ("1250.50")
 * with plain integer arithmetic. No floating point, no rounding, no currency
 * conversion, no locale grouping.
 *
 * Dates: the human `Date` column is the LOCAL calendar day of the record
 * ("2026-09-08"); `Created At` / `Updated At` are full ISO 8601 UTC
 * timestamps so exports stay machine-readable and sortable.
 *
 * Escaping follows RFC 4180: fields containing commas, quotes, newlines or
 * carriage returns are wrapped in double quotes, and embedded quotes are
 * doubled. Lines end with CRLF.
 */

/**
 * Columns of the transactions CSV, in order.
 *
 * `Recurring` (Phase 10) is an append-only extension: it marks whether a
 * row was GENERATED by a recurring rule — informational provenance only.
 * It is never an id (internal rule ids are not exposed) and importing it
 * never reconstructs a rule (spec §22). Older exports without the column
 * remain importable — the importer treats a missing `Recurring` column as
 * "No" (see `csvImport.ts`).
 */
export const CSV_COLUMNS = [
  'Type',
  'Date',
  'Amount',
  'Title',
  'Category',
  'Payment Method',
  'Source',
  'Note',
  'Created At',
  'Updated At',
  'Recurring',
] as const;

/**
 * Human indicator for recurring provenance: `Yes` when the row was
 * generated by a recurring rule, `No` for ordinary records.
 */
export function recurringCsvLabel(
  recurringRuleId: number | null | undefined,
): string {
  return recurringRuleId != null ? 'Yes' : 'No';
}

/** Local calendar day of an epoch-millis value ("2026-09-08"). */
export function formatDateColumn(ms: number): string {
  const date = new Date(ms);
  const year = date.getFullYear();
  const month = `${date.getMonth() + 1}`.padStart(2, '0');
  const day = `${date.getDate()}`.padStart(2, '0');
  return `${year}-${month}-${day}`;
}

/** Quotes the field only when RFC 4180 requires it. */
export function escapeCsvField(value: string): string {
  if (/[",\r\n]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

function csvTimestamp(ms: number): string {
  return new Date(ms).toISOString();
}

/**
 * Builds the ledger CSV from full expense rows (already joined with their
 * category names) and income rows. Rows are merged in ledger order: date
 * ascending, then type, then id — so the file reads like a chronological
 * account book. Categories are exported by NAME (not id).
 */
export function buildTransactionCsv(input: {
  expenses: ExpenseWithCategory[];
  income: Income[];
}): string {
  const rows: string[] = [CSV_COLUMNS.join(',')];

  const expenseRows = input.expenses.map(expense => ({
    sortDate: expense.date,
    sortType: 0,
    sortId: expense.id,
    cells: [
      'Expense',
      formatDateColumn(expense.date),
      formatMinorAsDecimal(expense.amount),
      expense.title,
      expense.categoryName,
      expense.paymentMethod,
      '', // Income has a Source; expenses do not.
      expense.note ?? '',
      csvTimestamp(expense.createdAt),
      csvTimestamp(expense.updatedAt),
      recurringCsvLabel(expense.recurringRuleId),
    ],
  }));

  const incomeRows = input.income.map(record => ({
    sortDate: record.date,
    sortType: 1,
    sortId: record.id,
    cells: [
      'Income',
      formatDateColumn(record.date),
      formatMinorAsDecimal(record.amount),
      '', // Title is an expense field; income carries Source instead.
      '', // Income is not categorized (free-text source by design).
      '', // No payment method on income.
      record.source,
      record.note ?? '',
      csvTimestamp(record.createdAt),
      csvTimestamp(record.updatedAt),
      recurringCsvLabel(record.recurringRuleId),
    ],
  }));

  const merged = [...expenseRows, ...incomeRows].sort(
    (a, b) =>
      a.sortDate - b.sortDate || a.sortType - b.sortType || a.sortId - b.sortId,
  );

  for (const row of merged) {
    rows.push(row.cells.map(escapeCsvField).join(','));
  }

  return `${rows.join('\r\n')}\r\n`;
}
